# Generated by Django 3.0.4 on 2020-04-14 15:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('YourJobAidApi', '0008_auto_20200414_2118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='title',
        ),
    ]
