# Generated by Django 3.0.4 on 2020-04-14 18:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('YourJobAidApi', '0013_post_category_read_only'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category_read_only',
        ),
    ]
