# Generated by Django 3.0.4 on 2020-04-14 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('YourJobAidApi', '0014_remove_post_category_read_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category_read_only',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='posts',
                                    to='YourJobAidApi.Category'),
            preserve_default=False,
        ),
    ]
