# Generated by Django 3.0.4 on 2020-04-16 22:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('YourJobAidApi', '0017_remove_post_category_identifying_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='count_post',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
