# Generated by Django 3.0.4 on 2020-04-16 23:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('YourJobAidApi', '0018_category_count_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='count_post',
        ),
    ]
