# Generated by Django 3.0.4 on 2020-04-17 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('YourJobAidApi', '0019_remove_category_count_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('message', models.TextField(blank=True, max_length=5000, null=True)),
                ('is_seen', models.BooleanField(blank=True, default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='category_read_only',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='totalposts',
                                    to='YourJobAidApi.Category'),
        ),
    ]
