# Generated by Django 3.0.4 on 2020-04-18 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YourJobAidApi', '0020_auto_20200418_0241'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='email_isSent',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
