# Generated by Django 3.0.4 on 2020-04-18 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YourJobAidApi', '0022_post_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, default='No data to show.', max_length=1000, null=True),
        ),
    ]
