# Generated by Django 3.0.4 on 2020-04-20 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('YourJobAidApi', '0028_auto_20200420_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category_read_only',
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='totalposts', to='YourJobAidApi.Category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(default='jobaid_default_post_pic/yourjobaid.jpg', upload_to='jobs/%Y/%m/%d/'),
        ),
    ]
