# Generated by Django 3.0.4 on 2020-04-20 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('YourJobAidApi', '0029_auto_20200420_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='replies',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='YourJobAidApi.Comment'),
        ),
    ]
